//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int Device_ID { get; set; }
        public string FNum { get; set; }
        public string Name { get; set; }
        public string MetrData { get; set; }
        public int IDObject { get; set; }
        public string Param { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string NoteText { get; set; }
    
        public virtual Object Object { get; set; }
    }
}
